### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by Nigota** [Nigota/DBLabsFinalWork#10]
А как там с docker?

**Comment by kkatekata** [comment]
пока что изучаю теорию по нему

**Comment by kkatekata** [comment]
не получается установить wsl и hyper через powershell от имени администратора и через командную строку, пробую разные версии docker и ищу другие пути решения проблемы.

**Comment by kkatekata** [comment]
у меня установился и открылся докер урааааааааааааа!!!!!!!перепробовав horizon,VMWare, virtualbox, дистрибутив linux, не удачную установку ubuntu, администраторский powershell с wsl2, я наконец то пришла к выводу что проблема была в самом bios и выключенной графе виртуализации на windows. Теперь начну делать задание

**Comment by Nigota** [comment]
Умница <3

**Comment by kkatekata** [comment]
пока что выложила код, позволяющий импортировать через localhost:8080 базу данных, я импортировала не нашу проектную ,а cd так как наша еще не готова. главное , что это работает . с нашей базой данных попробую это, когда она будет готова

**Comment by kkatekata** [comment]
вход через localhost:8080 - пользователь root, пароль password, база данных mysql

**Comment by kkatekata** [comment]
проверить наличие импортированной базы cd можно через выполнение sql запроса show databases

**Comment by Nigota** [comment]
Молодец!
