### ISSUE TITLE
jupiter файл

### ISSUE THREAD

**Issue by Nigota** [Nigota/DBLabsFinalWork#8]
Необходимо начать работу на jupiter файлом

**Comment by Nigota** [comment]
Сеня, сделай такие же как мы делали на лабах по питону
Но! не забудь вывод написать под графиками

**Comment by ArseniyZhuk** [comment]
Загрузил демо версию файла. Продолжаю работу

**Comment by ArseniyZhuk** [comment]
Немного исправил, пока работаю на другими графиками, думаю, какие лучше нарисовать, чтобы они были полезны.

**Comment by Nigota** [comment]
О! Выглядит очень круто. Особенно идея с тепловой картой корреляции параметров. Классная вещь!

**Comment by kkatekata** [comment]
графики очень хорошие, выводы по ним тоже, но есть вопрос по поводу "бесполезных" графиков. Можно ли их считать таковыми, если там есть какие-никакие, но всё же определенные более "плотные "скопления значений из расплывчатых. Может быть стоит в выводах сделать акцент на них тоже?

**Comment by ArseniyZhuk** [comment]
Доделал вроде бы все графики, которые можно считать "полезными" (это около 0.8 и больше).

**Comment by ArseniyZhuk** [comment]
В ответ Кате, думаю, что скопления говорят только об особенностях распределения данных в нашей выборке. Скопления есть и на некоторых "полезных" графиках, но они там ни о чём не говорят, мы смотрим только на общую картину графика, смотрим какой примерно коэффициент корреляции, нам важно положительный он или отрицательный.

**Comment by ArseniyZhuk** [comment]
Жду обратной связи, предложения о том, что можно добавить или исправить.

**Comment by kkatekata** [comment]
спасибо за пояснение ,Арсений, пока что всё хорошо, еще посмотрю чуть позже насчет добавлений

**Comment by barbaryman** [comment]
Арсений, графики, которые ты сделал, очень наглядно демонстрируют зависимости. Также ты дал объяснение каждому из графиков, что еще больше упрощает их понимание. Все доступно и понятно!
