### ISSUE TITLE
база данных

### ISSUE THREAD

**Issue by Nigota** [Nigota/DBLabsFinalWork#9]
Пора бы начать ее делать

**Comment by Nigota** [comment]
Я сделал ER-диаграмму, Артем, прежде, чем начать создавать БД, проверь правильность диаграммы

**Comment by ArtyomKuzmin** [comment]
Никита, я проверил диаграмму, сверил её с базой, диаграмма на все 100% правильная и соответствует базе данных!

**Comment by Nigota** [comment]
Окей, тогда начинай создавать базу данных - таблицы. Прежде, чем начать ей заполнять, загрузи код создания бд на гидхаб. Я проверю

**Comment by ArtyomKuzmin** [comment]
Таак, код создания базы данных загрузил, можешь глянуть, если всё хорошо, то начну заполнять.

**Comment by Nigota** [comment]
База данных не соответствует диаграмме. Надо сделать по диаграмме: и названия таблиц, и названия столбцов

**Comment by ArtyomKuzmin** [comment]
Проверил соответствие с диаграммой:
- исправил название таблицы
- исправил названия столбцов
- удалил лишние столбцы
- удалил лишние пробные данные, которые предназначались для удалённых столбцов
- добавил ещё один столбец type, которого не хватало ранее

**Comment by Nigota** [comment]
БД все равно не соответствует. Тебе надо создать 2 таблицы, а у тебя одна

**Comment by Nigota** [comment]
Артем, дедлайны горят!

**Comment by ArtyomKuzmin** [comment]
Никита, заметил опечатку в заголовке диаграммы, там должно быть CancerType, а не Canser, в базе данных указал верное название таблицы.
Про исправления БД:
- Добавил вторую таблицу
- Подкорректировал небольшие недочёты, связанные с типами данных
- Настроил вставление значений для примера

**Comment by Nigota** [comment]
Артем, спасибо за поправку диаграммы (позже подгружу). При создании бд таблицы никак не связываются. Нужно это указать. Например так - это было в нашей классной работе

`ALTER TABLE bookings
    ADD CONSTRAINT fk_bookings_memid FOREIGN KEY (memid) REFERENCES members(memid);`

После того как укажешь связь, можешь пробовать загрузить данные из csv в бд (для этого есть специальная функция - загугли в интернете)

**Comment by ArtyomKuzmin** [comment]
А у нас в csv ведь 30 столбцов, а по диаграмме их 10, то есть нужно всё таки добавить ещё столбцы?

**Comment by ArtyomKuzmin** [comment]
А у нас в csv ведь намного больше столбцов, а по диаграмме их меньше. Нужно получается ещё 20 столбцов добавить? Потому что там идут сначала с приставкой mean, потом с se, а потом с приставкой worst.

**Comment by Nigota** [comment]
Да. Верно подмечено! Нам остальные значения в базе данных не нужны. Остальные данные - это скользящее среднее из 3х и наименьший результат из 3х. Они нам ни к чему. Бери только те данные, которые имеют слово "mean"

**Comment by ArtyomKuzmin** [comment]
Ага, хорошо, понял на счёт количества столбцов. Связь таблиц по столбцам typeid добавил, как и указано в диаграмме.

**Comment by Nigota** [comment]
Молодец! Тогда осталось написать скрипт по заполнению таблицы. Совет: сначала сделай временную таблицу со всеми данными из csv, а потом из этой временной таблицы уже выгружай всё в базу данных (ну я бы так делал)

**Comment by ArtyomKuzmin** [comment]
Есть предположение, что можно таким вот образом выгрузить нужны столбцы из csv в бд, ну только вместо data.csv указать путь, предварительно скачав файл.
`LOAD DATA INFILE 'data.csv'
INTO TABLE CellNucleus
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(radius, typeid, texture, perimeter, area, smoothness, compactness, concavity, concave_points, symmetry, fractal_dimension);`

**Comment by Nigota** [comment]
Хорошо. Делай как считаешь правильным. Как всё получится - отпишись, попробую на своём пк запустить

**Comment by ArtyomKuzmin** [comment]
Внёс правки в базу данных, запусти код у себя, проверь корректность созданных таблиц. Если всё хорошо, то буду работать с переносом данных из csv файла.

**Comment by Nigota** [comment]
Всё работает, можешь загружать

**Comment by ArtyomKuzmin** [comment]
Отлично, сейчас буду переносить!

**Comment by ArtyomKuzmin** [comment]
Добавил выгрузку данных из csv файла, попробуй запустить код у себя. Вместо "путь к data.csv" укажи реальный пусть к data.csv на своём пк.

**Comment by Nigota** [comment]
Выгрузка не работает, пишет

`[Start] Executing MySQL query...
Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: 'M' for column 'typeid' at row 1
[Done] Finished MySQL query.`

Ты не правильно загружаешь данные. Надо к 25 декабря (вечер) уже всё закончить. Сначала убедись, что всё нормально загружается на твоем сервере, чтобы всё соответствовало  диаграмме, а потом уже загружай бд на сервер

**Comment by ArtyomKuzmin** [comment]
Попробовал импортировать данные из csv при помощи временной таблицы, попробуй запустить код у себя, `C:\Program Files\MySQL\MySQL Workbench 8.0 CE\data\data.csv` замени на путь к data.csv конкретно у тебя.

**Comment by Nigota** [comment]
Попробовал запустить. Ничего не работает. Артем, ты вообще у себя запускаешь программу?

**Comment by ArtyomKuzmin** [comment]
Загрузил отдельным файликом load.sql импорт из csv файла.

**Comment by Nigota** [comment]
Молодец! База данных работает исправно!

**Comment by Nigota** [comment]
На этом твоя часть работы закончена
